<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MT^3 - Academic Manager System - FCE UNRC</title>
    <meta name="description" content="Academic Manager System. Development by Carlos Dagorret - 2022">
    <meta name="keywords" content="Dagorret, MT3, FCE, UNRC">


    @vite(['resources/css/app.css'])


    <!-- Animation CSS-->
    <style>
        /* ----------------------------------------------
        * Generated by Animista
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        .slide-in-bottom {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both
        }

        .slide-in-bottom-h1 {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both
        }

        .slide-in-bottom-subtitle {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both
        }

        .fade-in {
            -webkit-animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both;
            animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both
        }

        .bounce-top-icons {
            -webkit-animation: bounce-top .9s 1s both;
            animation: bounce-top .9s 1s both
        }

        @-webkit-keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @-webkit-keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }
            24% {
                opacity: 1
            }
            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            25%, 55%, 75%, 87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }
            24% {
                opacity: 1
            }
            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            25%, 55%, 75%, 87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @-webkit-keyframes fade-in {
            0% {
                opacity: 0
            }
            100% {
                opacity: 1
            }
        }

        @keyframes fade-in {
            0% {
                opacity: 0
            }
            100% {
                opacity: 1
            }
        }
        /* source-sans-pro-regular - latin */
        @font-face {
            font-family: 'Source Sans Pro';
            font-style: normal;
            font-weight: 400;
            src: local(''),
            url('fonts/source-sans-pro-v21-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
            url('fonts/source-sans-pro-v21-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
        }

        /* source-sans-pro-700 - latin */
        @font-face {
            font-family: 'Source Sans Pro';
            font-style: normal;
            font-weight: 700;
            src: local(''),
            url('fonts/source-sans-pro-v21-latin-700.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
            url('fonts/source-sans-pro-v21-latin-700.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
        }

    </style>

</head>


<body class="leading-normal tracking-normal text-gray-900" style="font-family: 'Source Sans Pro', sans-serif;">


<div class="h-screen pb-14 bg-right bg-cover" style="background-image:url('img/bg.svg');">
    <!--Nav-->
    <div class="w-full container mx-auto p-6">

        <div class="w-full flex items-center justify-between">
            <a class="flex items-center text-indigo-400 no-underline hover:no-underline font-bold text-2xl lg:text-4xl"
               href="/">
                <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
                     width="100" height="82" viewBox="0 0 315.000000 94.000000"
                     preserveAspectRatio="xMidYMid meet">

                    <g transform="translate(0.000000,94.000000) scale(0.100000,-0.100000)"
                       fill="#000000" stroke="none">
                        <path d="M272 627 l-182 -182 183 -177 184 -176 179 179 179 179 -180 180
-180 180 -183 -183z m178 67 l0 -67 -87 -88 -87 -89 87 -89 87 -88 0 -67 c0
-36 -3 -66 -6 -66 -3 0 -78 68 -165 152 l-160 152 158 158 c87 87 161 158 165
158 5 0 8 -30 8 -66z m177 -401 l-157 -158 0 75 0 75 82 82 83 83 -83 83 -82
82 0 75 0 75 157 -158 158 -157 -158 -157z m-177 157 c0 -72 -4 -130 -8 -130
-4 0 -37 29 -72 65 l-64 65 64 65 c35 36 68 65 72 65 4 0 8 -58 8 -130z m87
-67 l-67 -68 0 135 0 135 67 -68 68 -67 -68 -67z"/>
                        <path d="M1020 455 l0 -285 60 0 59 0 3 147 3 148 65 -148 64 -148 54 3 54 3
63 145 64 145 1 -147 0 -148 60 0 60 0 0 285 0 286 -57 -3 -58 -3 -90 -197
c-49 -108 -92 -199 -95 -202 -3 -3 -48 87 -99 199 l-94 205 -58 0 -59 0 0
-285z"/>
                        <path d="M1720 685 l0 -55 70 0 70 0 0 -230 0 -230 60 0 60 0 0 230 0 230 70
0 70 0 0 55 0 55 -200 0 -200 0 0 -55z"/>
                        <path d="M2303 703 c-16 -21 -46 -62 -67 -90 l-38 -53 41 0 c33 0 49 7 81 36
l39 36 45 -37 c36 -29 51 -36 80 -33 l36 3 -62 87 c-56 78 -66 87 -95 88 -25
0 -37 -8 -60 -37z"/>
                        <path d="M2630 690 l0 -50 100 0 c55 0 100 -3 100 -7 0 -5 -23 -45 -50 -91
-28 -46 -50 -86 -50 -88 0 -3 13 -3 30 1 105 23 183 -94 111 -166 -46 -45
-125 -34 -165 23 -16 22 -16 23 -51 4 -60 -33 -61 -40 -12 -90 147 -147 402
-37 372 161 -7 51 -53 109 -103 130 -38 16 -40 8 40 136 26 43 48 80 48 83 0
2 -83 4 -185 4 l-185 0 0 -50z"/>
                    </g>
                </svg>
            </a>

            <div class="flex w-1/2 justify-end content-center">
                <a class="inline-block text-blue-300 no-underline hover:text-indigo-800 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4"
                   data-tippy-content="@twitter_handle" href="https://twitter.com/fceunrc">
                    <svg class="fill-current h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
                        <path
                            d="M30.063 7.313c-.813 1.125-1.75 2.125-2.875 2.938v.75c0 1.563-.188 3.125-.688 4.625a15.088 15.088 0 0 1-2.063 4.438c-.875 1.438-2 2.688-3.25 3.813a15.015 15.015 0 0 1-4.625 2.563c-1.813.688-3.75 1-5.75 1-3.25 0-6.188-.875-8.875-2.625.438.063.875.125 1.375.125 2.688 0 5.063-.875 7.188-2.5-1.25 0-2.375-.375-3.375-1.125s-1.688-1.688-2.063-2.875c.438.063.813.125 1.125.125.5 0 1-.063 1.5-.25-1.313-.25-2.438-.938-3.313-1.938a5.673 5.673 0 0 1-1.313-3.688v-.063c.813.438 1.688.688 2.625.688a5.228 5.228 0 0 1-1.875-2c-.5-.875-.688-1.813-.688-2.75 0-1.063.25-2.063.75-2.938 1.438 1.75 3.188 3.188 5.25 4.25s4.313 1.688 6.688 1.813a5.579 5.579 0 0 1 1.5-5.438c1.125-1.125 2.5-1.688 4.125-1.688s3.063.625 4.188 1.813a11.48 11.48 0 0 0 3.688-1.375c-.438 1.375-1.313 2.438-2.563 3.188 1.125-.125 2.188-.438 3.313-.875z"></path>
                    </svg>
                </a>
                <a class="inline-block text-blue-300 no-underline hover:text-indigo-800 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4 "
                   data-tippy-content="#facebook_id" href="https://www.facebook.com/fceunrc">
                    <svg class="fill-current h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
                        <path d="M19 6h5V0h-5c-3.86 0-7 3.14-7 7v3H8v6h4v16h6V16h5l1-6h-6V7c0-.542.458-1 1-1z"></path>
                    </svg>
                </a>
            </div>

        </div>

    </div>

    <!--Main-->
    <div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">

        <!--Left Col-->
        <div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
            <h1 class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1">
                Bienvenido</h1>
            <p class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">
                Systema de Administración Académica de la <a href="https://www.eco.unrc.edu.ar" target="_blank" class="underline">FCE::UNRC</a></p>

            <p class="text-blue-400 font-bold pb-8 lg:pb-6 text-center md:text-left fade-in"></p>
            <div class="flex w-full justify-center md:justify-start pb-24 lg:pb-0 fade-in">
                <button class="bg-purple-700 hover:bg-purple-400 text-white font-bold py-2 px-4 border border-purple-700 rounded">
                    <i class="fa-solid fa-right-to-bracket fa-beat-fade" style="--fa-beat-fade-opacity: 0.1; --fa-beat-fade-scale: 1.25;" ></i>
                    &nbspIngresar
                </button>
            </div>

        </div>

        <!--Right Col-->
        <div class="w-full xl:w-3/5 py-6 overflow-y-hidden">
            <img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="img/presentation.svg" style="width: 50%; height: 50%">
        </div>

        <!--Footer-->
        <div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
            &copy; &nbsp <i class="fa-solid fa-heart fa-beat  --fa-animation-duration: 2s; --fa-secondary-color: gold;" style="color:mediumvioletred"></i> Carlos Dagorret 2022 in FCE UNRC

        </div>

    </div>




</div>



@vite(['resources/jquery/jquery-3.6.1.js'])

</body>

</html>
